site_name: p3orm
repo_url: https://github.com/rafalstapinski/p3orm
repo_name: stapinskirafal/p3orm
docs_dir: mkdocs
site_dir: docs

nav:
  - About: index.md
  - Getting Started: getting_started.md
  - Tutorial:
    - Relationships: tutorial/relationships.md
    - Complex Queries: tutorial/complex_queries.md
    - Connection Pool: tutorial/connection_pool.md
    - Multiple Databases: tutorial/multiple_databases.md

theme:
  name: material
  favicon: img/favicon.png
  palette:
    primary: deep orange
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

