name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Check out
      - uses: actions/checkout@v2

      # Set up Python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.0'

      # Install poetry
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.12"

      # Install deps
      - run: poetry install

      # Build
      - run: poetry build

      # Publish
      - run: poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
