on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11

    steps:
      # - name: Check out
      - uses: actions/checkout@v2

      # - Name: Set up Python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.0'
      
      # - name: Install postgresql
      - run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg ${{ matrix.postgres-version }}" > /etc/apt/sources.list.d/pgdg.list'
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo sh -c 'echo "Package: *" > /etc/apt/preferences.d/psql'
          sudo sh -c 'echo "Pin: release c=${{ matrix.poxtgresql-version }}" >> /etc/apt/preferences.d/psql'
          sudo sh -c 'echo "Pin-Priority: 1000" >> /etc/apt/preferences.d/psql'
          sudo apt-get update -o Dir::Etc::sourcelist="/etc/apt/sources.list.d/pgdg.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
          sudo apt install -y postgresql-${{ matrix.postgres-version }} postgresql-client-${{ matrix.postgres-version }}
  
      # - name: Install poetry
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.12"

      # - name: poetry
      - run: which poetry
      - run: poetry --version

      # - name: Check pg_config
      - run: which pg_config

      # - name: Test
      - run: poetry run pytest test

      # - name: Cache
      # - uses: actions/cache@v2
