name: Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ["3.12"]
      fail-fast: false

    steps:
      # Check out
      - uses: actions/checkout@v2

      # Set up Python
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Start postgresql
      - run: sudo systemctl start postgresql.service

      # Check sqlite version
      - run: sqlite3 --version

      # Install poetry
      - uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: '1.7.1'

      # Install deps
      - run: poetry install

      # # Test SQLite
      # - run: poetry run pytest test/sqlite
      #
      # # Test Postgres
      # - run: poetry run pytest test/postgres

      # isort
      - run: poetry run isort --sp pyproject.toml --check .

      # black
      - run: poetry run black --config pyproject.toml --check .

      # pylint
      # - run: poetry run pylint p3orm/

      - name: ruff
        run: poetry run ruff p3orm/

      # check versions match
      - run: poetry run python scripts/assert_package_versions_match.py
