name: Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
      fail-fast: false

    steps:
      # Check out
      - uses: actions/checkout@v2

      # Set up Python
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Start postgresql
      - run: sudo systemctl start postgresql.service

      # Check sqlite version
      - run: sqlite3 --version

      # Install poetry
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.5.1"

      # Install deps
      - run: poetry install

      # Test SQLite
      - run: poetry run pytest test/sqlite

      # Test Postgres
      - run: poetry run pytest test/postgres

      # isort
      - run: poetry run isort --sp pyproject.toml --check .

      # black
      - run: poetry run black --config pyproject.toml --check .

      # pylint
      - run: poetry run pylint p3orm/

      # check versions match
      - run: poetry run python scripts/assert_package_versions_match.py
